version: 2

sources:
  - name: raw
    database: ZOOM
    schema: RAW
    tables:
      - name: customer_details

models:
  - name: customer_details_bronze
    description: "Bronze layer model"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: customer_name
        description: "Customer full name"
        tests:
          - not_null


